name: model_viewer_plus_ff
description: A Flutter widget for rendering interactive 3D models in the glTF and GLB formats (Flutterflow adaption)
version: 4.0.0
repository: https://github.com/famenft/model_viewer_plus_ff.dart
topics:
  - model-viewer
  - model
platforms:
  android:
  ios:
  web:
environment:
  sdk: ^3.1.0
  flutter: '>=3.13.0'

dependencies:
  android_intent_plus: ^4.0.2
  flutter:
    sdk: flutter
  path: ^1.8.3
  url_launcher: ^6.1.0
  webview_flutter: 4.0.5
  webview_flutter_android: 3.3.1
  webview_flutter_wkwebview: 3.1.1

dev_dependencies:
  carapacik_lints: ^1.5.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
